version: '3.8'

services:
  api:
    build: ./services/api
    ports:
      - "8080:80"
    depends_on:
      - postgres
    environment:
      - ConnectionStrings__Default=Host=postgres;Port=5432;Database=mydb;Username=myuser;Password=mypassword

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./services/db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:
