// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using carelinkAPI.Data;

#nullable disable

namespace carelinkAPI.Migrations
{
    [DbContext(typeof(ClDbContext))]
    [Migration("20250408094542_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("carelinkAPI.Models.Opholdssted", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Opholdssteder");
                });

            modelBuilder.Entity("carelinkAPI.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("OpholdsstedId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OpholdsstedId");

                    b.ToTable("Personer");
                });

            modelBuilder.Entity("carelinkAPI.Models.PersonRelation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PersonAId")
                        .HasColumnType("integer");

                    b.Property<int>("PersonBId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PersonAId");

                    b.HasIndex("PersonBId");

                    b.ToTable("PersonRelationer");
                });

            modelBuilder.Entity("carelinkAPI.Models.Person", b =>
                {
                    b.HasOne("carelinkAPI.Models.Opholdssted", "Opholdssted")
                        .WithMany()
                        .HasForeignKey("OpholdsstedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Opholdssted");
                });

            modelBuilder.Entity("carelinkAPI.Models.PersonRelation", b =>
                {
                    b.HasOne("carelinkAPI.Models.Person", "PersonA")
                        .WithMany()
                        .HasForeignKey("PersonAId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("carelinkAPI.Models.Person", "PersonB")
                        .WithMany()
                        .HasForeignKey("PersonBId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PersonA");

                    b.Navigation("PersonB");
                });
#pragma warning restore 612, 618
        }
    }
}
